### ISSUE TITLE
there is no package called ‘buildtools’

### ISSUE THREAD

**Issue by pfuehrlich-pik** [r-universe/pik-piam#1]
All package builds last Friday failed with `there is no package called ‘buildtools’`, see [here](https://github.com/r-universe/pik-piam/actions/runs/3068517258/jobs/4956081116). Do you know what the problem is @jeroen ? Maybe that dependency should be installed in the GitHub Action?

**Comment by jeroen** [comment]
This was a temporary glitch introduced on Friday that was fixed on Saturday. Are you still seeing this?

**Comment by pfuehrlich-pik** [comment]
Thanks for the quick response! Seems to work again now.
