### ISSUE TITLE
DLL 'purrr' not found: maybe not installed for this architecture?

### ISSUE THREAD

**Issue by pfuehrlich-pik** [r-universe/pik-piam#3]
The GitHub Action fails on Windows using R 4.1 trying to install our `lucode2` package. Specifically it seems to fail while trying to load `purrr` (a dependency), see [here](https://github.com/r-universe/pik-piam/actions/runs/3845702579/jobs/6550232428#step:9:49). I have the feeling this needs fixing in the Action, maybe something along the lines of `install.packages("purrr", libs_only = TRUE)` or `install.packages(..., INSTALL_opts = "--no-multiarch")`. What's your take on this @jeroen ?
Thanks in advance, your help is always very much appreciated!
Best,
Pascal

**Comment by jeroen** [comment]
This is due to a bug in the latest purrr release: see https://github.com/tidyverse/purrr/pull/1017 and https://github.com/tidyverse/purrr/issues/1039

It should be fixed automatically when they release the new version this week.

**Comment by pfuehrlich-pik** [comment]
Great, thanks!
