### ISSUE TITLE
team name is null in r-universe R package title

### ISSUE THREAD

**Issue by jnnsbrr** [r-universe/pik-piam#4]
Our team name **PIK-LPJmL** is not visible on our package page: https://pik-piam.r-universe.dev/ui#package:lpjmlkit

Instead it shows **null/lpjmlkit**.  What I also noticed is that in the listing of all packages it says "lpjml" instead of "PIK-LPJmL" - our team name.
For other packages combinations with other teams work, see https://pik-piam.r-universe.dev/ui#package:iamc or https://pik-piam.r-universe.dev/ui#package:HARr

Adding @pfuehrlich-pik 

Many thanks in advance 🙏

**Comment by jnnsbrr** [comment]
@pfuehrlich-pik , currently ropensci uses gitlab. Can you change it to the github mirror?

**Comment by pfuehrlich-pik** [comment]
I did. I believe as soon as you push another change it will be built again which should hopefully fixes the `null`. Let me know if it works :)

**Comment by jnnsbrr** [comment]
It worked, thanks a lot!
